name: "plano_alimentar_ai"
description: "Um aplicativo para planejamento de refeições personalizado."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  cupertino_icons: ^1.0.6
  percent_indicator: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - dev_assets/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#0C39CC"
  adaptive_icon_foreground: "dev_assets/icon_mpa_ai.png"